openapi: 3.1.0
info:
  title: XP history
  version: v0
servers:
- url: http://localhost:8099/api/v1
  description: Generated server url
paths:
  /xp/history:
    get:
      tags:
      - xp-history-controller
      operationId: history
      parameters:
      - name: days
        in: query
        required: false
        schema:
          type: integer
          format: int32
          maximum: 90
          minimum: 1
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/XpHistoryResponseDTO'
components:
  schemas:
    OwnerSeries:
      type: object
      properties:
        ownerType:
          type: string
          enum:
          - USER
          - CATEGORY
          - HABIT
          - ROUTINE
        ownerId:
          type: string
          format: uuid
        values:
          type: array
          items:
            type: number
            format: double
    XpHistoryResponseDTO:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        days:
          type: array
          items:
            type: string
            format: date
        series:
          type: array
          items:
            $ref: '#/components/schemas/OwnerSeries'
