openapi: 3.1.0
info:
  title: User photo
  version: v0
servers:
- url: http://localhost:8099/api/v1
  description: Generated server url
paths:
  /user/photo:
    post:
      tags:
      - user-photo-controller
      operationId: upload
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
              - file
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /user/photo/{userId}:
    get:
      tags:
      - user-photo-controller
      operationId: serve
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: binary
