openapi: 3.1.0
info:
  title: Habits
  version: v0
servers:
- url: http://localhost:8099/api/v1
  description: Generated server url
paths:
  /habit:
    get:
      tags:
      - habit-controller
      operationId: getHabits
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HabitResponseDTO'
    put:
      tags:
      - habit-controller
      operationId: editHabit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditHabitDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
    post:
      tags:
      - habit-controller
      operationId: createHabit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateHabitDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /habit/{habitId}:
    delete:
      tags:
      - habit-controller
      operationId: deleteHabit
      parameters:
      - name: habitId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 256
          minLength: 2
        description:
          type: string
          maxLength: 256
          minLength: 0
        iconId:
          type: string
        xpProgress:
          $ref: '#/components/schemas/XpProgress'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
      - name
    CreateHabitDTO:
      type: object
      properties:
        name:
          type: string
          maxLength: 256
          minLength: 2
        description:
          type: string
          maxLength: 256
          minLength: 0
        motivationalPhrase:
          type: string
          maxLength: 256
          minLength: 0
        iconId:
          type: string
          minLength: 1
        importance:
          type: integer
          format: int32
          maximum: 5
          minimum: 1
        dificulty:
          type: integer
          format: int32
          maximum: 5
          minimum: 1
        categoriesId:
          type: array
          items:
            type: string
            format: uuid
          minItems: 1
        experience:
          type: string
          enum:
          - BEGINNER
          - INTERMEDIARY
          - ADVANCED
      required:
      - categoriesId
      - dificulty
      - experience
      - iconId
      - importance
      - name
    EditHabitDTO:
      type: object
      properties:
        habitId:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 256
        description:
          type: string
          maxLength: 256
        motivationalPhrase:
          type: string
          maxLength: 256
        iconId:
          type: string
        importance:
          type: integer
          format: int32
          maximum: 5
          minimum: 1
        dificulty:
          type: integer
          format: int32
          maximum: 5
          minimum: 1
        categoriesId:
          type: array
          items:
            type: string
            format: uuid
          minItems: 1
      required:
      - categoriesId
      - dificulty
      - importance
    HabitResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        motivationalPhrase:
          type: string
        iconId:
          type: string
        importance:
          type: integer
          format: int32
        dificulty:
          type: integer
          format: int32
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        xp:
          type: number
          format: double
        actualLevelXp:
          type: number
          format: double
        nextLevelXp:
          type: number
          format: double
        level:
          type: integer
          format: int32
        currentStreak:
          type: integer
          format: int32
        bestStreak:
          type: integer
          format: int32
        totalCheckIns:
          type: integer
          format: int32
        firstCheckInDate:
          type: string
          format: date
        streakDormant:
          type: boolean
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
        routines:
          type: object
          additionalProperties:
            type: string
    XpProgress:
      type: object
      properties:
        xp:
          type: number
          format: double
        level:
          type: integer
          format: int32
        actualLevelXp:
          type: number
          format: double
        nextLevelXp:
          type: number
          format: double
