openapi: 3.1.0
info:
  title: Tasks
  version: v0
servers:
- url: http://localhost:8099/api/v1
  description: Generated server url
paths:
  /task:
    get:
      tags:
      - task-controller
      operationId: getTasks
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponseDTO'
    put:
      tags:
      - task-controller
      operationId: editTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditTaskRequestDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
    post:
      tags:
      - task-controller
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequestDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /task/{taskId}:
    delete:
      tags:
      - task-controller
      operationId: deleteTask
      parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
components:
  schemas:
    CategoryMiniDTO:
      type: object
      properties:
        name:
          type: string
        iconId:
          type: string
    CreateTaskRequestDTO:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
          minLength: 2
        description:
          type: string
          maxLength: 255
          minLength: 0
        iconId:
          type: string
          minLength: 1
        importance:
          type: integer
          format: int32
          maximum: 5
          minimum: 1
        difficulty:
          type: integer
          format: int32
          maximum: 5
          minimum: 1
        categoriesId:
          type: array
          items:
            type: string
            format: uuid
        oneTimeTask:
          type: boolean
      required:
      - difficulty
      - iconId
      - importance
      - name
    EditTaskRequestDTO:
      type: object
      properties:
        taskId:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 255
        iconId:
          type: string
        importance:
          type: integer
          format: int32
          maximum: 5
          minimum: 1
        difficulty:
          type: integer
          format: int32
          maximum: 5
          minimum: 1
        categoriesId:
          type: array
          items:
            type: string
            format: uuid
        oneTimeTask:
          type: boolean
      required:
      - difficulty
      - importance
    TaskResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        iconId:
          type: string
        importance:
          type: integer
          format: int32
        difficulty:
          type: integer
          format: int32
        categories:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CategoryMiniDTO'
        oneTimeTask:
          type: boolean
        currentStreak:
          type: integer
          format: int32
        bestStreak:
          type: integer
          format: int32
        totalCheckIns:
          type: integer
          format: int32
        firstCheckInDate:
          type: string
          format: date
        streakDormant:
          type: boolean
        markedToDelete:
          type: string
          format: date
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
