openapi: 3.1.0
info:
  title: Project docs
  version: v0
servers:
- url: http://localhost:8099/api/v1
  description: Generated server url
paths:
  /docs/projects/topics:
    get:
      tags:
      - project-docs-controller
      operationId: getTopics
      parameters:
      - name: locale
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectTopicListItemDTO'
  /docs/projects/topics/{key}:
    get:
      tags:
      - project-docs-controller
      operationId: getTopic
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
      - name: locale
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectTopicDetailDTO'
components:
  schemas:
    ProjectTopicDetailDTO:
      type: object
      properties:
        key:
          type: string
        title:
          type: string
        docMarkdown:
          type: string
        diagramMermaid:
          type: string
        designTopicKey:
          type: string
        architectureTopicKey:
          type: string
        repositoryUrl:
          type: string
        tags:
          type: string
        updatedAt:
          type: string
          format: date-time
    ProjectTopicListItemDTO:
      type: object
      properties:
        key:
          type: string
        title:
          type: string
        summary:
          type: string
        orderIndex:
          type: integer
          format: int32
        updatedAt:
          type: string
          format: date-time
        status:
          type: string
        tags:
          type: string
