openapi: 3.1.0
info:
  title: Blog docs
  version: v0
servers:
- url: http://localhost:8099/api/v1
  description: Generated server url
paths:
  /docs/blog/topics:
    get:
      tags:
      - blog-docs-controller
      operationId: getTopics_1
      parameters:
      - name: locale
        in: query
        required: false
        schema:
          type: string
      - name: category
        in: query
        required: false
        schema:
          type: string
      - name: tag
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlogTopicListItemDTO'
  /docs/blog/topics/{key}:
    get:
      tags:
      - blog-docs-controller
      operationId: getTopic_1
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
      - name: locale
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BlogTopicDetailDTO'
components:
  schemas:
    BlogTopicDetailDTO:
      type: object
      properties:
        key:
          type: string
        title:
          type: string
        docMarkdown:
          type: string
        category:
          type: string
        tags:
          type: string
        featured:
          type: boolean
        publishedAt:
          type: string
          format: date-time
        coverColor:
          type: string
        coverEmoji:
          type: string
        author:
          type: string
        updatedAt:
          type: string
          format: date-time
    BlogTopicListItemDTO:
      type: object
      properties:
        key:
          type: string
        title:
          type: string
        summary:
          type: string
        category:
          type: string
        tags:
          type: string
        featured:
          type: boolean
        publishedAt:
          type: string
          format: date-time
        coverColor:
          type: string
        coverEmoji:
          type: string
        author:
          type: string
        updatedAt:
          type: string
          format: date-time
