openapi: 3.1.0
info:
  title: Routines
  version: v0
servers:
- url: http://localhost:8099/api/v1
  description: Generated server url
paths:
  /routine/{id}:
    get:
      tags:
      - routine-controller
      operationId: getDiaryRoutineById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DiaryRoutineResponseDTO'
    put:
      tags:
      - routine-controller
      operationId: updateDiaryRoutine
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiaryRoutineRequestDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DiaryRoutineResponseDTO'
    delete:
      tags:
      - routine-controller
      operationId: deleteDiaryRoutine
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
  /routine:
    get:
      tags:
      - routine-controller
      operationId: getAllDiaryRoutines
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DiaryRoutineResponseDTO'
    post:
      tags:
      - routine-controller
      operationId: createDiaryRoutine
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiaryRoutineRequestDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DiaryRoutineResponseDTO'
  /routine/skip:
    post:
      tags:
      - routine-controller
      operationId: skipItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SkipGroupRequestDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RefreshUiDTO'
  /routine/check:
    post:
      tags:
      - routine-controller
      operationId: checkItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckGroupRequestDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RefreshUiDTO'
  /routine/today:
    get:
      tags:
      - routine-controller
      operationId: getTodayRoutineScheduled
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DiaryRoutineResponseDTO'
components:
  schemas:
    BaseCheck:
      type: object
      properties:
        id:
          type: string
          format: uuid
        checkDate:
          type: string
          format: date
        checkTime:
          type: string
        checked:
          type: boolean
        skipped:
          type: boolean
        xpGenerated:
          type: number
          format: double
    CheckGroupRequestDTO:
      type: object
      properties:
        routineId:
          type: string
          format: uuid
        taskGroupDTO:
          $ref: '#/components/schemas/TaskGroupRequestDTO'
        habitGroupDTO:
          $ref: '#/components/schemas/HabitGroupRequestDTO'
        date:
          type: string
          format: date
    DiaryRoutineRequestDTO:
      type: object
      properties:
        name:
          type: string
        iconId:
          type: string
        routineSections:
          type: array
          items:
            $ref: '#/components/schemas/RoutineSectionRequestDTO'
    DiaryRoutineResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        iconId:
          type: string
        routineSections:
          type: array
          items:
            $ref: '#/components/schemas/RoutineSectionResponseDTO'
        schedule:
          $ref: '#/components/schemas/ScheduleResponseDTO'
        xp:
          type: number
          format: double
        actualLevelXp:
          type: number
          format: double
        nextLevelXp:
          type: number
          format: double
        level:
          type: integer
          format: int32
    HabitGroupCheck:
      type: object
      properties:
        id:
          type: string
          format: uuid
        checkDate:
          type: string
          format: date
        checkTime:
          type: string
        checked:
          type: boolean
        skipped:
          type: boolean
        xpGenerated:
          type: number
          format: double
    HabitGroupDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        habitId:
          type: string
          format: uuid
        startTime:
          type: string
        endTime:
          type: string
        habitGroupCheck:
          type: array
          items:
            $ref: '#/components/schemas/HabitGroupCheck'
    HabitGroupRequestDTO:
      type: object
      properties:
        habitGroupId:
          type: string
          format: uuid
        startTime:
          type: string
    HabitGroupResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        habitId:
          type: string
          format: uuid
        startTime:
          type: string
        endTime:
          type: string
        habitGroupChecks:
          type: array
          items:
            $ref: '#/components/schemas/HabitGroupCheck'
    RefreshItemCheckedDTO:
      type: object
      properties:
        groupItemId:
          type: string
          format: uuid
        check:
          $ref: '#/components/schemas/BaseCheck'
    RefreshObjectDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        xp:
          type: number
          format: double
        level:
          type: integer
          format: int32
        actualLevelXp:
          type: number
          format: double
        nextLevelXp:
          type: number
          format: double
        currentStreak:
          type: integer
          format: int32
        bestStreak:
          type: integer
          format: int32
        totalCheckIns:
          type: integer
          format: int32
    RefreshUiDTO:
      type: object
      properties:
        refreshUser:
          $ref: '#/components/schemas/RefreshUserDTO'
        refreshCategories:
          type: array
          items:
            $ref: '#/components/schemas/RefreshObjectDTO'
        refreshHabit:
          $ref: '#/components/schemas/RefreshObjectDTO'
        refreshItemChecked:
          $ref: '#/components/schemas/RefreshItemCheckedDTO'
    RefreshUserDTO:
      type: object
      properties:
        currentConstance:
          type: integer
          format: int32
        alreadyIncreaseConstanceToday:
          type: boolean
        maxConstance:
          type: integer
          format: int32
        xp:
          type: number
          format: double
        level:
          type: integer
          format: int32
        actualLevelXp:
          type: number
          format: double
        nextLevelXp:
          type: number
          format: double
    RoutineSectionRequestDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        iconId:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        taskGroup:
          type: array
          items:
            $ref: '#/components/schemas/TaskGroupDTO'
        habitGroup:
          type: array
          items:
            $ref: '#/components/schemas/HabitGroupDTO'
        favorite:
          type: boolean
    RoutineSectionResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        iconId:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        taskGroup:
          type: array
          items:
            $ref: '#/components/schemas/TaskGroupResponseDTO'
        habitGroup:
          type: array
          items:
            $ref: '#/components/schemas/HabitGroupResponseDTO'
        favorite:
          type: boolean
    ScheduleResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        days:
          type: array
          items:
            type: string
            enum:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
          uniqueItems: true
    SkipGroupRequestDTO:
      type: object
      properties:
        routineId:
          type: string
          format: uuid
        taskGroupDTO:
          $ref: '#/components/schemas/TaskGroupRequestDTO'
        habitGroupDTO:
          $ref: '#/components/schemas/HabitGroupRequestDTO'
        date:
          type: string
          format: date
        skip:
          type: boolean
    TaskGroupCheck:
      type: object
      properties:
        id:
          type: string
          format: uuid
        checkDate:
          type: string
          format: date
        checkTime:
          type: string
        checked:
          type: boolean
        skipped:
          type: boolean
        xpGenerated:
          type: number
          format: double
    TaskGroupDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        taskId:
          type: string
          format: uuid
        startTime:
          type: string
        endTime:
          type: string
        taskGroupCheck:
          type: array
          items:
            $ref: '#/components/schemas/TaskGroupCheck'
    TaskGroupRequestDTO:
      type: object
      properties:
        taskGroupId:
          type: string
          format: uuid
        startTime:
          type: string
    TaskGroupResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        taskId:
          type: string
          format: uuid
        startTime:
          type: string
        endTime:
          type: string
        taskGroupChecks:
          type: array
          items:
            $ref: '#/components/schemas/TaskGroupCheck'
